name: Upload Secret to GCP Secret Manager

on:
  push:
    branches: [ main ]

jobs:
  upload_secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: <your-gcp-project-id>
        service_account_email: <your-service-account-email>
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Create and Upload Secret
      env:
        SECRET_NAME: my-secret
        SECRET_VALUE: my-secret-value
      run: |
        echo $SECRET_VALUE | gcloud secrets create $SECRET_NAME --data-file=-

    - name: Verify Secret Upload
      run: |
        gcloud secrets describe my-secret
