name: Update Secrets Workflow

on:
  push:
    branches:
      - main

jobs:
  create-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: YOUR_PROJECT_ID
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Create new secret
        run: |
          gcloud secrets create my-new-secret --replication-policy automatic

  update-secret:
    runs-on: ubuntu-latest
    needs: create-secret
    steps:
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: YOUR_PROJECT_ID
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Update secret version
        run: |
          SECRET_VERSION=$(gcloud secrets versions create my-new-secret --data-file /path/to/my/secret --replication-policy automatic --format 'value(name)')
          echo "::set-output name=secret_version::$SECRET_VERSION"
