name: Update Secret in GCP

on:
  push:
    branches:
      - main

jobs:
  update-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: <YOUR_PROJECT_ID>
          service_account_email: <YOUR_SERVICE_ACCOUNT_EMAIL>
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Create or update secret
        run: |
          gcloud secrets create <SECRET_NAME> \
          --data-file=<PATH_TO_SECRET_DATA_FILE> \
          --replication-policy=automatic \
          --locations=<GCP_SECRET_LOCATION>

      - name: Update secret version
        run: |
          gcloud secrets versions add <SECRET_NAME> \
          --data-file=<PATH_TO_NEW_SECRET_DATA_FILE> \
          --automatic

