name: 'Terraform CI'

on:
  #workflow_dispatch:
  push:
    branches:
    - bigtable-test
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory : bigtable

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
      
    - id: 'auth'
      name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v0'
      with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      
    - name: GCP setup
      uses: 'google-github-actions/setup-gcloud@v0.6.0'
      with:
          project_id: 'hca-dei-sbx'
      
      
    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1


    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    - name: terraform plan and apply
      run: | 
      
           terraform init
           terraform plan
           terraform apply --auto-approve
           #terraform destroy --auto-approve
